### ISSUE TITLE
"Friendly mine" links point to old LIS mines

### ISSUE THREAD

**Issue by sammyjava** [asherpasha/thalemine#13]
Hi! I just noticed a bunch of 440s in our server log, and see that the requests all come from version GETs from Toronto, and discovered that the "friendly mine" URIs to the genus-specific LIS mines are pointing to our old mines:

![image](https://github.com/asherpasha/thalemine/assets/5657219/66085973-fff4-4fc0-914f-09e5c59f90de)

Some time ago we renamed the LIS genus-specific mines to use the genera names:

- https://mines.legumeinfo.org/aeschynomenemine/  **AeschynomeneMine** Aeschynomene evenia
- https://mines.legumeinfo.org/arachismine/  **ArachisMine**  Arachis cardenasii, duranensis, ipaensis, hypogaea 
- https://mines.legumeinfo.org/cajanusmine/ **CajanusMine** Cajanus cajan
- https://mines.legumeinfo.org/cicermine/ **CicerMine** Cicer arietinum, echinospermum, reticulatum
- https://mines.legumeinfo.org/glycinemine/ **GlycineMine** Glycine max, soja and a number of perennial species
- https://mines.legumeinfo.org/lensmine/ **LensMine** Lens culinaris, ervoide
- https://mines.legumeinfo.org/lupinusmine/ **LupinusMine** Lupinus albus, angustifolius
- https://mines.legumeinfo.org/medicagomine/ **MedicagoMine** Medicago polymorpha, ruthenica, sativa, truncatula
- https://mines.legumeinfo.org/phaseolusmine/ **PhaseolusMine** Phaseolus acutifolius, vulgaris, lunatus
- https://mines.legumeinfo.org/vignamine/ **VignaMine** Vigna angularis, radiata, unguiculata

LegumeMine is still the same (/legumemine).

We'd appreciate you updating those "friendly mine" URIs! Thanks! (FYI, @adf-ncgr)

**Comment by asherpasha** [comment]
I have updated the links in ThaleMine.
Thanks.

**Comment by sammyjava** [comment]
Thanks!!!

**Comment by adf-ncgr** [comment]
Thanks Asher! I can see the updated sections, but as far as I can tell everything is still returning no results for any of the legume-based mines. I think (but @sammyjava will know better) that this is a consequence of the fact that the existing friendly-mines strategy depends on the existence of Homologues, whereas our mines store homology relations in terms of gene family assignments that imply that all members of the same family are homologous. I thought we had at one point figured out how to "fool" other mines into thinking we did this according to the standard data model, but I'm not %100 sure. In any case, unless there is some evidence that we are being "friendly" maybe just removing the links altogether makes more sense- but I will defer to you and @sammyjava on that.

**Comment by sammyjava** [comment]
Correct, good call, Andrew. The LIS "friendliness" is a custom gene-family based "friendliness" for querying the similar genes. This is not, of course, present on ThaleMine so the LIS mines are, in fact, "unfriendly" and should be removed.

**Comment by asherpasha** [comment]
I have removed the links.

**Comment by adf-ncgr** [comment]
thanks Asher, and sorry for the delayed acknowledgment!
